version: '3.0'
services:
  mongo:
    image: mongo:4
    container_name: container_mongo_will
    ports:
      - 27017:27017
    restart: always
  api:
    image: node:16-alpine
    container_name: container_api_will
    restart: always
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
      - SERVER_PORT=3001
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    command: bash -c "npm install && npm start"